---

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        goarch: ["386", amd64, arm64]
    steps:
    - uses: actions/checkout@v3

    - uses: wangyoucao577/go-release-action@v1
      env:
        CGO_ENABLED: "0"
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: ${{ matrix.goarch }}
        goversion: "1.16"
        extra_files: LICENSE README.md
        sha256sum: true
